//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.strewi.database.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal EnumNames() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("de.strewi.database.Resources.EnumNames", typeof(EnumNames).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aluminium.
        /// </summary>
        public static string Alloy {
            get {
                return ResourceManager.GetString("Alloy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Messing.
        /// </summary>
        public static string Brass {
            get {
                return ResourceManager.GetString("Brass", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Abziehbild.
        /// </summary>
        public static string Decal {
            get {
                return ResourceManager.GetString("Decal", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ätzung.
        /// </summary>
        public static string Etching {
            get {
                return ResourceManager.GetString("Etching", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unbekannt.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zinkdruckguss.
        /// </summary>
        public static string ZincDieCast {
            get {
                return ResourceManager.GetString("ZincDieCast", resourceCulture);
            }
        }
    }
}
