//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.strewi.database.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal PropertyNames() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("de.strewi.database.Resources.PropertyNames", typeof(PropertyNames).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Stadt.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bestätigung.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ungefähres Jahr.
        /// </summary>
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vorname.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Beginn der Produktion.
        /// </summary>
        public static string FoundedAt {
            get {
                return ResourceManager.GetString("FoundedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Material.
        /// </summary>
        public static string HeadbadgeMaterial {
            get {
                return ResourceManager.GetString("HeadbadgeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geschichte.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Horizontaler Abstand.
        /// </summary>
        public static string HorizontalDistance {
            get {
                return ResourceManager.GetString("HorizontalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nachname.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hersteller.
        /// </summary>
        public static string ManufacturerId {
            get {
                return ResourceManager.GetString("ManufacturerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mitgliedsnummer.
        /// </summary>
        public static string MemberNumber {
            get {
                return ResourceManager.GetString("MemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Befestigung.
        /// </summary>
        public static string MountingPoints {
            get {
                return ResourceManager.GetString("MountingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hinweise.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Anzahl der Bohrungen.
        /// </summary>
        public static string NumberOfMountingPoints {
            get {
                return ResourceManager.GetString("NumberOfMountingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Übernommen in.
        /// </summary>
        public static string OvertakenAt {
            get {
                return ResourceManager.GetString("OvertakenAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Übernommen durch.
        /// </summary>
        public static string OvertakenById {
            get {
                return ResourceManager.GetString("OvertakenById", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Passwort.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ende der Produktion.
        /// </summary>
        public static string StoppedProductionAt {
            get {
                return ResourceManager.GetString("StoppedProductionAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bild.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Verwendete Farben.
        /// </summary>
        public static string UsedColors {
            get {
                return ResourceManager.GetString("UsedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Verwendet von.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Verwendet bis.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vertikaler Abstand.
        /// </summary>
        public static string VerticalDistance {
            get {
                return ResourceManager.GetString("VerticalDistance", resourceCulture);
            }
        }
    }
}
